# Generated by Django 4.2 on 2023-04-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_keeping_unit', models.CharField(max_length=200)),
                ('seats', models.PositiveSmallIntegerField()),
                ('placed_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='management.room')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_keeping_unit', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('B', 'Bench chair'), ('D', 'Dining chair'), ('A', 'Armchair')], max_length=1)),
                ('placed_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairs', to='management.room')),
            ],
        ),
    ]
