# Generated by Django 4.2 on 2023-04-08 14:30

from django.db import migrations, models


def copy_answer_to_answer_list(apps):
    Question = apps.get_model('quiz', 'Question')
    for question in Question.objects.all():
        answers = question.answer_list.all()
        for answer in answers:
            if answer.is_correct:
                new_answer = question.answer_list.create(answer_text=answer.answer_text)
                new_answer.is_correct = True
                new_answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_list',
            field=models.ManyToManyField(
                help_text='This is a list of answers.',
                to='quiz.answer',
                verbose_name='answer list'
            ),
        ),
        migrations.RunPython(copy_answer_to_answer_list),
    ]
