# Generated by Django 4.2 on 2023-04-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_answer_question_answer_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_list',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
